/*
 * Copyright 2016 SRI International
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.07.10 at 05:21:16 PM MDT 
//


package com.sri.pal.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ConstraintInputFuncType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ConstraintInputFuncType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice minOccurs="0">
 *         &lt;group ref="{}paramInput"/>
 *       &lt;/choice>
 *       &lt;attribute name="function" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ConstraintInputFuncType", propOrder = {
    "inputList",
    "inputRef",
    "inputUnknown",
    "inputConstant",
    "inputFunc"
})
public class ConstraintInputFuncType {

    protected ConstraintInputListType inputList;
    protected ConstraintInputRefType inputRef;
    protected ConstraintInputUnknownType inputUnknown;
    protected ConstraintInputConstantType inputConstant;
    protected ConstraintInputFuncType inputFunc;
    @XmlAttribute(required = true)
    protected String function;

    /**
     * Gets the value of the inputList property.
     * 
     * @return
     *     possible object is
     *     {@link ConstraintInputListType }
     *     
     */
    public ConstraintInputListType getInputList() {
        return inputList;
    }

    /**
     * Sets the value of the inputList property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConstraintInputListType }
     *     
     */
    public void setInputList(ConstraintInputListType value) {
        this.inputList = value;
    }

    /**
     * Gets the value of the inputRef property.
     * 
     * @return
     *     possible object is
     *     {@link ConstraintInputRefType }
     *     
     */
    public ConstraintInputRefType getInputRef() {
        return inputRef;
    }

    /**
     * Sets the value of the inputRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConstraintInputRefType }
     *     
     */
    public void setInputRef(ConstraintInputRefType value) {
        this.inputRef = value;
    }

    /**
     * Gets the value of the inputUnknown property.
     * 
     * @return
     *     possible object is
     *     {@link ConstraintInputUnknownType }
     *     
     */
    public ConstraintInputUnknownType getInputUnknown() {
        return inputUnknown;
    }

    /**
     * Sets the value of the inputUnknown property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConstraintInputUnknownType }
     *     
     */
    public void setInputUnknown(ConstraintInputUnknownType value) {
        this.inputUnknown = value;
    }

    /**
     * Gets the value of the inputConstant property.
     * 
     * @return
     *     possible object is
     *     {@link ConstraintInputConstantType }
     *     
     */
    public ConstraintInputConstantType getInputConstant() {
        return inputConstant;
    }

    /**
     * Sets the value of the inputConstant property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConstraintInputConstantType }
     *     
     */
    public void setInputConstant(ConstraintInputConstantType value) {
        this.inputConstant = value;
    }

    /**
     * Gets the value of the inputFunc property.
     * 
     * @return
     *     possible object is
     *     {@link ConstraintInputFuncType }
     *     
     */
    public ConstraintInputFuncType getInputFunc() {
        return inputFunc;
    }

    /**
     * Sets the value of the inputFunc property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConstraintInputFuncType }
     *     
     */
    public void setInputFunc(ConstraintInputFuncType value) {
        this.inputFunc = value;
    }

    /**
     * Gets the value of the function property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFunction() {
        return function;
    }

    /**
     * Sets the value of the function property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFunction(String value) {
        this.function = value;
    }

}
