/*
 * Copyright 2016 SRI International
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.13 at 04:29:47 PM MDT 
//


package com.sri.pal.training.core.basemodels;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EqualityIssue complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EqualityIssue">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="location1" type="{}ArgumentLocation"/>
 *         &lt;element name="location2" type="{}ArgumentLocation"/>
 *         &lt;element name="constraint" type="{}EqualityConstraint" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="negated" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="support" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EqualityIssue", propOrder = {
    "location1",
    "location2",
    "constraint"
})
public class EqualityIssueBase {

    @XmlElement(required = true)
    protected com.sri.pal.training.core.assessment.ArgumentLocation location1;
    @XmlElement(required = true)
    protected com.sri.pal.training.core.assessment.ArgumentLocation location2;
    protected EqualityConstraintBase constraint;
    @XmlAttribute(name = "negated")
    protected Boolean negated;
    @XmlAttribute(name = "support")
    protected Boolean support;

    /**
     * Gets the value of the location1 property.
     * 
     * @return
     *     possible object is
     *     {@link com.sri.pal.training.core.assessment.ArgumentLocation }
     *     
     */
    public com.sri.pal.training.core.assessment.ArgumentLocation getLocation1() {
        return location1;
    }

    /**
     * Sets the value of the location1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link com.sri.pal.training.core.assessment.ArgumentLocation }
     *     
     */
    public void setLocation1(com.sri.pal.training.core.assessment.ArgumentLocation value) {
        this.location1 = value;
    }

    /**
     * Gets the value of the location2 property.
     * 
     * @return
     *     possible object is
     *     {@link com.sri.pal.training.core.assessment.ArgumentLocation }
     *     
     */
    public com.sri.pal.training.core.assessment.ArgumentLocation getLocation2() {
        return location2;
    }

    /**
     * Sets the value of the location2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link com.sri.pal.training.core.assessment.ArgumentLocation }
     *     
     */
    public void setLocation2(com.sri.pal.training.core.assessment.ArgumentLocation value) {
        this.location2 = value;
    }

    /**
     * Gets the value of the constraint property.
     * 
     * @return
     *     possible object is
     *     {@link EqualityConstraintBase }
     *     
     */
    public EqualityConstraintBase getConstraint() {
        return constraint;
    }

    /**
     * Sets the value of the constraint property.
     * 
     * @param value
     *     allowed object is
     *     {@link EqualityConstraintBase }
     *     
     */
    public void setConstraint(EqualityConstraintBase value) {
        this.constraint = value;
    }

    /**
     * Gets the value of the negated property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isNegated() {
        if (negated == null) {
            return false;
        } else {
            return negated;
        }
    }

    /**
     * Sets the value of the negated property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setNegated(Boolean value) {
        this.negated = value;
    }

    /**
     * Gets the value of the support property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isSupport() {
        if (support == null) {
            return false;
        } else {
            return support;
        }
    }

    /**
     * Sets the value of the support property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setSupport(Boolean value) {
        this.support = value;
    }

}
