/*
 * Copyright 2016 SRI International
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.13 at 04:29:47 PM MDT 
//


package com.sri.pal.training.core.basemodels;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import com.sri.pal.training.core.exercise.Datafile;
import com.sri.pal.training.core.exercise.Problem;
import com.sri.pal.training.core.exercise.Solution;


/**
 * <p>Java class for Exercise complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Exercise">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="extra_step_warnings" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="datafile" type="{}Datafile" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="action_model" type="{http://www.w3.org/2001/XMLSchema}anyURI" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="editor_data" type="{}EditorData" minOccurs="0"/>
 *         &lt;element name="html" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="problem" type="{}Problem"/>
 *         &lt;element name="setup_procedure" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="solution" type="{}Solution" minOccurs="0"/>
 *         &lt;element name="success_html" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Exercise", propOrder = {
    "name",
    "description",
    "extraStepWarnings",
    "datafile",
    "actionModel",
    "editorData",
    "html",
    "problem",
    "setupProcedure",
    "solution",
    "successHtml"
})
public class ExerciseBase {

    @XmlElement(required = true)
    protected String name;
    protected String description;
    @XmlElement(name = "extra_step_warnings")
    protected Boolean extraStepWarnings;
    protected List<Datafile> datafile;
    @XmlElement(name = "action_model")
    @XmlSchemaType(name = "anyURI")
    protected List<String> actionModel;
    @XmlElement(name = "editor_data")
    protected EditorDataBase editorData;
    protected String html;
    @XmlElement(required = true)
    protected Problem problem;
    @XmlElement(name = "setup_procedure")
    protected String setupProcedure;
    protected Solution solution;
    @XmlElement(name = "success_html")
    protected String successHtml;
    @XmlAttribute(name = "id", required = true)
    protected String id;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the extraStepWarnings property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isExtraStepWarnings() {
        return extraStepWarnings;
    }

    /**
     * Sets the value of the extraStepWarnings property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setExtraStepWarnings(Boolean value) {
        this.extraStepWarnings = value;
    }

    /**
     * Gets the value of the datafile property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the datafile property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDatafile().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Datafile }
     * 
     * 
     */
    public List<Datafile> getDatafile() {
        if (datafile == null) {
            datafile = new ArrayList<Datafile>();
        }
        return this.datafile;
    }

    /**
     * Gets the value of the actionModel property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the actionModel property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getActionModel().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getActionModel() {
        if (actionModel == null) {
            actionModel = new ArrayList<String>();
        }
        return this.actionModel;
    }

    /**
     * Gets the value of the editorData property.
     * 
     * @return
     *     possible object is
     *     {@link EditorDataBase }
     *     
     */
    public EditorDataBase getEditorData() {
        return editorData;
    }

    /**
     * Sets the value of the editorData property.
     * 
     * @param value
     *     allowed object is
     *     {@link EditorDataBase }
     *     
     */
    public void setEditorData(EditorDataBase value) {
        this.editorData = value;
    }

    /**
     * Gets the value of the html property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHtml() {
        return html;
    }

    /**
     * Sets the value of the html property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHtml(String value) {
        this.html = value;
    }

    /**
     * Gets the value of the problem property.
     * 
     * @return
     *     possible object is
     *     {@link Problem }
     *     
     */
    public Problem getProblem() {
        return problem;
    }

    /**
     * Sets the value of the problem property.
     * 
     * @param value
     *     allowed object is
     *     {@link Problem }
     *     
     */
    public void setProblem(Problem value) {
        this.problem = value;
    }

    /**
     * Gets the value of the setupProcedure property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSetupProcedure() {
        return setupProcedure;
    }

    /**
     * Sets the value of the setupProcedure property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSetupProcedure(String value) {
        this.setupProcedure = value;
    }

    /**
     * Gets the value of the solution property.
     * 
     * @return
     *     possible object is
     *     {@link Solution }
     *     
     */
    public Solution getSolution() {
        return solution;
    }

    /**
     * Sets the value of the solution property.
     * 
     * @param value
     *     allowed object is
     *     {@link Solution }
     *     
     */
    public void setSolution(Solution value) {
        this.solution = value;
    }

    /**
     * Gets the value of the successHtml property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSuccessHtml() {
        return successHtml;
    }

    /**
     * Sets the value of the successHtml property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSuccessHtml(String value) {
        this.successHtml = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

}
