/*
 * Copyright 2016 SRI International
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.19 at 08:44:59 PM MST 
//


package com.sri.pal.training.core.basemodels;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MissingAtomIssue complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MissingAtomIssue">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="functor" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="max_display_index" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="min_display_index" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="pref_display_index" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="step" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MissingAtomIssue", propOrder = {
    "functor",
    "maxDisplayIndex",
    "minDisplayIndex",
    "prefDisplayIndex",
    "step"
})
public class MissingAtomIssueBase {

    @XmlElement(required = true)
    protected String functor;
    @XmlElement(name = "max_display_index")
    protected Integer maxDisplayIndex;
    @XmlElement(name = "min_display_index")
    protected Integer minDisplayIndex;
    @XmlElement(name = "pref_display_index")
    protected int prefDisplayIndex;
    @XmlElement(required = true)
    protected String step;

    /**
     * Gets the value of the functor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFunctor() {
        return functor;
    }

    /**
     * Sets the value of the functor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFunctor(String value) {
        this.functor = value;
    }

    /**
     * Gets the value of the maxDisplayIndex property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getMaxDisplayIndex() {
        return maxDisplayIndex;
    }

    /**
     * Sets the value of the maxDisplayIndex property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMaxDisplayIndex(Integer value) {
        this.maxDisplayIndex = value;
    }

    /**
     * Gets the value of the minDisplayIndex property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getMinDisplayIndex() {
        return minDisplayIndex;
    }

    /**
     * Sets the value of the minDisplayIndex property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMinDisplayIndex(Integer value) {
        this.minDisplayIndex = value;
    }

    /**
     * Gets the value of the prefDisplayIndex property.
     * 
     */
    public int getPrefDisplayIndex() {
        return prefDisplayIndex;
    }

    /**
     * Sets the value of the prefDisplayIndex property.
     * 
     */
    public void setPrefDisplayIndex(int value) {
        this.prefDisplayIndex = value;
    }

    /**
     * Gets the value of the step property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStep() {
        return step;
    }

    /**
     * Sets the value of the step property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStep(String value) {
        this.step = value;
    }

}
