/*
 * Copyright 2016 SRI International
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.13 at 04:29:47 PM MDT 
//


package com.sri.pal.training.core.basemodels;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.sri.pal.training.core.basemodels package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Assessment_QNAME = new QName("", "assessment");
    private final static QName _Response_QNAME = new QName("", "response");
    private final static QName _Exercise_QNAME = new QName("", "exercise");
    private final static QName _Option_QNAME = new QName("", "option");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.sri.pal.training.core.basemodels
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AssessmentBase }
     * 
     */
    public AssessmentBase createAssessmentBase() {
        return new AssessmentBase();
    }

    /**
     * Create an instance of {@link ResponseBase }
     * 
     */
    public ResponseBase createResponseBase() {
        return new ResponseBase();
    }

    /**
     * Create an instance of {@link ExerciseBase }
     * 
     */
    public ExerciseBase createExerciseBase() {
        return new ExerciseBase();
    }

    /**
     * Create an instance of {@link OptionBase }
     * 
     */
    public OptionBase createOptionBase() {
        return new OptionBase();
    }

    /**
     * Create an instance of {@link ExtraAtomsIssueBase }
     * 
     */
    public ExtraAtomsIssueBase createExtraAtomsIssueBase() {
        return new ExtraAtomsIssueBase();
    }

    /**
     * Create an instance of {@link TaskBase }
     * 
     */
    public TaskBase createTaskBase() {
        return new TaskBase();
    }

    /**
     * Create an instance of {@link DatafileBase }
     * 
     */
    public DatafileBase createDatafileBase() {
        return new DatafileBase();
    }

    /**
     * Create an instance of {@link QueryIssueBase }
     * 
     */
    public QueryIssueBase createQueryIssueBase() {
        return new QueryIssueBase();
    }

    /**
     * Create an instance of {@link ArgumentLocationBase }
     * 
     */
    public ArgumentLocationBase createArgumentLocationBase() {
        return new ArgumentLocationBase();
    }

    /**
     * Create an instance of {@link EqualityIssueBase }
     * 
     */
    public EqualityIssueBase createEqualityIssueBase() {
        return new EqualityIssueBase();
    }

    /**
     * Create an instance of {@link StepBase }
     * 
     */
    public StepBase createStepBase() {
        return new StepBase();
    }

    /**
     * Create an instance of {@link QueryConstraintBase }
     * 
     */
    public QueryConstraintBase createQueryConstraintBase() {
        return new QueryConstraintBase();
    }

    /**
     * Create an instance of {@link EditorDataBase }
     * 
     */
    public EditorDataBase createEditorDataBase() {
        return new EditorDataBase();
    }

    /**
     * Create an instance of {@link StateConstraintBase }
     * 
     */
    public StateConstraintBase createStateConstraintBase() {
        return new StateConstraintBase();
    }

    /**
     * Create an instance of {@link HintSequenceBase }
     * 
     */
    public HintSequenceBase createHintSequenceBase() {
        return new HintSequenceBase();
    }

    /**
     * Create an instance of {@link SubTaskBase }
     * 
     */
    public SubTaskBase createSubTaskBase() {
        return new SubTaskBase();
    }

    /**
     * Create an instance of {@link TaskResponseBase }
     * 
     */
    public TaskResponseBase createTaskResponseBase() {
        return new TaskResponseBase();
    }

    /**
     * Create an instance of {@link SolutionBase }
     * 
     */
    public SolutionBase createSolutionBase() {
        return new SolutionBase();
    }

    /**
     * Create an instance of {@link AssessedResponseIndexesBase }
     * 
     */
    public AssessedResponseIndexesBase createAssessedResponseIndexesBase() {
        return new AssessedResponseIndexesBase();
    }

    /**
     * Create an instance of {@link OrderingIssueBase }
     * 
     */
    public OrderingIssueBase createOrderingIssueBase() {
        return new OrderingIssueBase();
    }

    /**
     * Create an instance of {@link MissingAtomIssueBase }
     * 
     */
    public MissingAtomIssueBase createMissingAtomIssueBase() {
        return new MissingAtomIssueBase();
    }

    /**
     * Create an instance of {@link StateIssueBase }
     * 
     */
    public StateIssueBase createStateIssueBase() {
        return new StateIssueBase();
    }

    /**
     * Create an instance of {@link ValueConstraintBase }
     * 
     */
    public ValueConstraintBase createValueConstraintBase() {
        return new ValueConstraintBase();
    }

    /**
     * Create an instance of {@link ConstraintArgumentBase }
     * 
     */
    public ConstraintArgumentBase createConstraintArgumentBase() {
        return new ConstraintArgumentBase();
    }

    /**
     * Create an instance of {@link SubTaskDelineationBase }
     * 
     */
    public SubTaskDelineationBase createSubTaskDelineationBase() {
        return new SubTaskDelineationBase();
    }

    /**
     * Create an instance of {@link AtomBase }
     * 
     */
    public AtomBase createAtomBase() {
        return new AtomBase();
    }

    /**
     * Create an instance of {@link EqualityConstraintBase }
     * 
     */
    public EqualityConstraintBase createEqualityConstraintBase() {
        return new EqualityConstraintBase();
    }

    /**
     * Create an instance of {@link ValueIssueBase }
     * 
     */
    public ValueIssueBase createValueIssueBase() {
        return new ValueIssueBase();
    }

    /**
     * Create an instance of {@link TaskSolutionBase }
     * 
     */
    public TaskSolutionBase createTaskSolutionBase() {
        return new TaskSolutionBase();
    }

    /**
     * Create an instance of {@link TypeIssueBase }
     * 
     */
    public TypeIssueBase createTypeIssueBase() {
        return new TypeIssueBase();
    }

    /**
     * Create an instance of {@link DemonstratedValueBase }
     * 
     */
    public DemonstratedValueBase createDemonstratedValueBase() {
        return new DemonstratedValueBase();
    }

    /**
     * Create an instance of {@link TaskAssessmentBase }
     * 
     */
    public TaskAssessmentBase createTaskAssessmentBase() {
        return new TaskAssessmentBase();
    }

    /**
     * Create an instance of {@link TypeConstraintBase }
     * 
     */
    public TypeConstraintBase createTypeConstraintBase() {
        return new TypeConstraintBase();
    }

    /**
     * Create an instance of {@link ValueBase }
     * 
     */
    public ValueBase createValueBase() {
        return new ValueBase();
    }

    /**
     * Create an instance of {@link ParameterBase }
     * 
     */
    public ParameterBase createParameterBase() {
        return new ParameterBase();
    }

    /**
     * Create an instance of {@link OrderingConstraintBase }
     * 
     */
    public OrderingConstraintBase createOrderingConstraintBase() {
        return new OrderingConstraintBase();
    }

    /**
     * Create an instance of {@link ProblemBase }
     * 
     */
    public ProblemBase createProblemBase() {
        return new ProblemBase();
    }

    /**
     * Create an instance of {@link OptionSetBase }
     * 
     */
    public OptionSetBase createOptionSetBase() {
        return new OptionSetBase();
    }

    /**
     * Create an instance of {@link LinkBase }
     * 
     */
    public LinkBase createLinkBase() {
        return new LinkBase();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AssessmentBase }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "assessment")
    public JAXBElement<AssessmentBase> createAssessment(AssessmentBase value) {
        return new JAXBElement<AssessmentBase>(_Assessment_QNAME, AssessmentBase.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ResponseBase }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "response")
    public JAXBElement<ResponseBase> createResponse(ResponseBase value) {
        return new JAXBElement<ResponseBase>(_Response_QNAME, ResponseBase.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ExerciseBase }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "exercise")
    public JAXBElement<ExerciseBase> createExercise(ExerciseBase value) {
        return new JAXBElement<ExerciseBase>(_Exercise_QNAME, ExerciseBase.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OptionBase }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "option")
    public JAXBElement<OptionBase> createOption(OptionBase value) {
        return new JAXBElement<OptionBase>(_Option_QNAME, OptionBase.class, null, value);
    }

}
