/*
 * Copyright 2016 SRI International
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.13 at 04:29:47 PM MDT 
//


package com.sri.pal.training.core.basemodels;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import com.sri.pal.training.core.response.SubTaskDelineation;


/**
 * <p>Java class for TaskResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TaskResponse">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="demo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="seconds_elapsed" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="delineation" type="{}SubTaskDelineation" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TaskResponse", propOrder = {
    "demo",
    "secondsElapsed",
    "delineations"
})
public class TaskResponseBase {

    @XmlElement(required = true)
    protected String demo;
    @XmlElement(name = "seconds_elapsed")
    protected int secondsElapsed;
    @XmlElement(name = "delineation")
    protected List<SubTaskDelineation> delineations;

    /**
     * Gets the value of the demo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDemo() {
        return demo;
    }

    /**
     * Sets the value of the demo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDemo(String value) {
        this.demo = value;
    }

    /**
     * Gets the value of the secondsElapsed property.
     * 
     */
    public int getSecondsElapsed() {
        return secondsElapsed;
    }

    /**
     * Sets the value of the secondsElapsed property.
     * 
     */
    public void setSecondsElapsed(int value) {
        this.secondsElapsed = value;
    }

    /**
     * Gets the value of the delineations property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the delineations property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDelineations().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SubTaskDelineation }
     * 
     * 
     */
    public List<SubTaskDelineation> getDelineations() {
        if (delineations == null) {
            delineations = new ArrayList<SubTaskDelineation>();
        }
        return this.delineations;
    }

}
