/*
 * Copyright 2016 SRI International
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.13 at 04:29:47 PM MDT 
//


package com.sri.pal.training.core.basemodels;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import com.sri.pal.training.core.assessment.AssessedResponseIndexes;
import com.sri.pal.training.core.assessment.EqualityIssue;
import com.sri.pal.training.core.assessment.ExtraAtomsIssue;
import com.sri.pal.training.core.assessment.MissingAtomIssue;
import com.sri.pal.training.core.assessment.OrderingIssue;
import com.sri.pal.training.core.assessment.QueryIssue;
import com.sri.pal.training.core.assessment.StateIssue;
import com.sri.pal.training.core.assessment.TypeIssue;
import com.sri.pal.training.core.assessment.ValueIssue;


/**
 * <p>Java class for TaskAssessment complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TaskAssessment">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="response_indexes" type="{}AssessedResponseIndexes"/>
 *         &lt;element name="equality_issue" type="{}EqualityIssue" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="extra_atoms_issue" type="{}ExtraAtomsIssue" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="missing_atom_issue" type="{}QueryIssue" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="ordering_issue" type="{}OrderingIssue" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="query_issue" type="{}QueryIssue" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="state_issue" type="{}StateIssue" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="value_issue" type="{}ValueIssue" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="type_issue" type="{}TypeIssue" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TaskAssessment", propOrder = {
    "responseIndexes",
    "equalityIssues",
    "extraAtomsIssues",
    "missingAtomIssues",
    "orderingIssues",
    "queryIssues",
    "stateIssues",
    "valueIssues",
    "typeIssues"
})
public class TaskAssessmentBase {

    @XmlElement(name = "response_indexes", required = true)
    protected AssessedResponseIndexes responseIndexes;
    @XmlElement(name = "equality_issue")
    protected List<EqualityIssue> equalityIssues;
    @XmlElement(name = "extra_atoms_issue")
    protected List<ExtraAtomsIssue> extraAtomsIssues;
    @XmlElement(name = "missing_atom_issue")
    protected List<MissingAtomIssue> missingAtomIssues;
    @XmlElement(name = "ordering_issue")
    protected List<OrderingIssue> orderingIssues;
    @XmlElement(name = "query_issue")
    protected List<QueryIssue> queryIssues;
    @XmlElement(name = "state_issue")
    protected List<StateIssue> stateIssues;
    @XmlElement(name = "value_issue")
    protected List<ValueIssue> valueIssues;
    @XmlElement(name = "type_issue")
    protected List<TypeIssue> typeIssues;

    /**
     * Gets the value of the responseIndexes property.
     * 
     * @return
     *     possible object is
     *     {@link AssessedResponseIndexes }
     *     
     */
    public AssessedResponseIndexes getResponseIndexes() {
        return responseIndexes;
    }

    /**
     * Sets the value of the responseIndexes property.
     * 
     * @param value
     *     allowed object is
     *     {@link AssessedResponseIndexes }
     *     
     */
    public void setResponseIndexes(AssessedResponseIndexes value) {
        this.responseIndexes = value;
    }

    /**
     * Gets the value of the equalityIssues property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the equalityIssues property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEqualityIssues().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EqualityIssue }
     * 
     * 
     */
    public List<EqualityIssue> getEqualityIssues() {
        if (equalityIssues == null) {
            equalityIssues = new ArrayList<EqualityIssue>();
        }
        return this.equalityIssues;
    }

    /**
     * Gets the value of the extraAtomsIssues property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the extraAtomsIssues property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getExtraAtomsIssues().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ExtraAtomsIssue }
     * 
     * 
     */
    public List<ExtraAtomsIssue> getExtraAtomsIssues() {
        if (extraAtomsIssues == null) {
            extraAtomsIssues = new ArrayList<ExtraAtomsIssue>();
        }
        return this.extraAtomsIssues;
    }

    /**
     * Gets the value of the missingAtomIssues property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the missingAtomIssues property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMissingAtomIssues().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MissingAtomIssue }
     * 
     * 
     */
    public List<MissingAtomIssue> getMissingAtomIssues() {
        if (missingAtomIssues == null) {
            missingAtomIssues = new ArrayList<MissingAtomIssue>();
        }
        return this.missingAtomIssues;
    }

    /**
     * Gets the value of the orderingIssues property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the orderingIssues property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOrderingIssues().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OrderingIssue }
     * 
     * 
     */
    public List<OrderingIssue> getOrderingIssues() {
        if (orderingIssues == null) {
            orderingIssues = new ArrayList<OrderingIssue>();
        }
        return this.orderingIssues;
    }

    /**
     * Gets the value of the queryIssues property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the queryIssues property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getQueryIssues().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link QueryIssue }
     * 
     * 
     */
    public List<QueryIssue> getQueryIssues() {
        if (queryIssues == null) {
            queryIssues = new ArrayList<QueryIssue>();
        }
        return this.queryIssues;
    }

    /**
     * Gets the value of the stateIssues property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the stateIssues property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStateIssues().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link StateIssue }
     * 
     * 
     */
    public List<StateIssue> getStateIssues() {
        if (stateIssues == null) {
            stateIssues = new ArrayList<StateIssue>();
        }
        return this.stateIssues;
    }

    /**
     * Gets the value of the valueIssues property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the valueIssues property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getValueIssues().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ValueIssue }
     * 
     * 
     */
    public List<ValueIssue> getValueIssues() {
        if (valueIssues == null) {
            valueIssues = new ArrayList<ValueIssue>();
        }
        return this.valueIssues;
    }

    /**
     * Gets the value of the typeIssues property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the typeIssues property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTypeIssues().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TypeIssue }
     * 
     * 
     */
    public List<TypeIssue> getTypeIssues() {
        if (typeIssues == null) {
            typeIssues = new ArrayList<TypeIssue>();
        }
        return this.typeIssues;
    }

}
